# Generated by Django 5.1.7 on 2025-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slip',
            name='user_address',
        ),
        migrations.AddField(
            model_name='slip',
            name='user_uid',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
