# Generated by Django 5.1.7 on 2025-03-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='imei_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
