# Generated by Django 5.1.7 on 2025-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('user_address', models.TextField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('device_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Warranty',
        ),
    ]
