# Generated by Django 5.1.7 on 2025-03-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0002_slip_imei_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='imei_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
