# Generated by Django 5.1.7 on 2025-03-08 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0002_slip_delete_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slip',
            old_name='device_name',
            new_name='ipfs_hash',
        ),
        migrations.AddField(
            model_name='slip',
            name='temp_file',
            field=models.FileField(null=True, upload_to='temp'),
        ),
        migrations.AddField(
            model_name='slip',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 8, 12, 0)),
            preserve_default=False,
        ),
    ]
